// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClC8NiUxzJAH8vID1SnSChJv40H_rRCts',
    appId: '1:670017745754:web:65b2714afda4abe9d03963',
    messagingSenderId: '670017745754',
    projectId: 'study-lib-mgmt-2026',
    authDomain: 'study-lib-mgmt-2026.firebaseapp.com',
    storageBucket: 'study-lib-mgmt-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3U_lnXLEF0V0_VkjhIiNYymyrNsEiuk',
    appId: '1:670017745754:android:a9e44e1d53b3c1e7d03963',
    messagingSenderId: '670017745754',
    projectId: 'study-lib-mgmt-2026',
    storageBucket: 'study-lib-mgmt-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdooGjfGr20pF_BXC9knZTzT9cAAJTyo',
    appId: '1:670017745754:ios:f6f904c0104f79b1d03963',
    messagingSenderId: '670017745754',
    projectId: 'study-lib-mgmt-2026',
    storageBucket: 'study-lib-mgmt-2026.firebasestorage.app',
    iosBundleId: 'com.studylibrary.app',
  );
}
